import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import Layout from "../component/Layout";
export default function Home() {
  const router = useRouter();
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>eco</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <button
            onClick={() => {
              window.analytics.track("Article Bookmarked", {
                title: "Snow Fall",
                subtitle: "The Avalanche at Tunnel Creek",
                author: "John Branch",
              });
              router.push("/argha");
            }}
          >
            Click Arijit
          </button>
        </main>
      </div>
    </Layout>
  );
}
